name: Checkmarx AST Scan

on:
  push:
    branches:
      - main

permissions:
        security-events: write
        actions: read
        contents: read
        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Checkmarx AST Scan
    #  uses: Checkmarx/ast-github-action@2.0.18 #Github Action version
      with:
        base_uri: https://ast.checkmarx.net
        cx_tenant: nfr_optiv
        cx_client_id: ${{ secrets.CLIENT_ID }}
        cx_client_secret: ${{ secrets.CLIENT_SECRET }}
        project_name: CxVedant
        github_token: ${{ secrets.GITHUB_TOKEN }}
        additional_params: --report-format sarif --output-path .
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with: 
        # Path to SARIF file relative to the root of the repository
        sarif_file: cx_result.sarif
